

# Metrics configuration for Spring Actuator and also prometheus, it's the same for all profiles
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  metrics:
    export:
      atlas:
        enabled: false
spring:
  application:
    name: service-a
server:
  port: 8800

eureka:
  maxRetries: 100
  requestRetryDelay: 2000
  instance:
    prefer-ip-address: true
    hostname: service-a
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka,http://eureka-1.eureka.default.svc.cluster.local:8761/eureka,http://eureka-2.eureka.default.svc.cluster.local:8761/eureka
